### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Elyahou**

### CODE REVIEW

**Comment by DaveWM** [comment]
+1

**Comment by dribnet** [comment]
Thanks, looks good! I'm traveling currently, so please allow me an extra day or two to try this out and verify the unit tests.

**Comment by dribnet** [comment]
Thanks for this! Will roll a new strokes release with these changes and upstream mrhyde changes.

**Comment by DaveWM** [comment]
@dribnet any idea when you'll be able to do a new release?

**Comment by factom** [comment]
I made a new mrhyde release, but then this branch was having problems in testing - I'm not sure if the compiler changed. I'll try again this weekend and post the issue.

**Comment by dribnet** [comment]
I made a new mrhyde release, but then this branch was having problems in testing - I'm not sure if the compiler changed. I'll try again this weekend and post the issue.

**Pull request merged**
